trees:
  d3d:
    - \D3D::TOP.ELECTRONS.ECE.TECEF:TECEF01
    - \D3D::TOP.ELECTRONS.ECE.TECEF:TECEF02
    - \D3D::TOP.ELECTRONS.ECE.TECEF:TECEF03
    - \D3D::TOP.ELECTRONS.ECE.TECEF:TECEF04
    - \D3D::TOP.ELECTRONS.ECE.TECEF:TECEF05
    - \D3D::TOP.ELECTRONS.ECE.TECEF:TECEF06
    - \D3D::TOP.ELECTRONS.ECE.TECEF:TECEF07
    - \D3D::TOP.ELECTRONS.ECE.TECEF:TECEF08
    - \D3D::TOP.ELECTRONS.ECE.TECEF:TECEF09
    - \D3D::TOP.ELECTRONS.ECE.TECEF:TECEF10
    - \D3D::TOP.ELECTRONS.ECE.TECEF:TECEF11
    - \D3D::TOP.ELECTRONS.ECE.TECEF:TECEF12
    - \D3D::TOP.ELECTRONS.ECE.TECEF:TECEF13
    - \D3D::TOP.ELECTRONS.ECE.TECEF:TECEF14
    - \D3D::TOP.ELECTRONS.ECE.TECEF:TECEF15
    - \D3D::TOP.ELECTRONS.ECE.TECEF:TECEF16
    - \D3D::TOP.ELECTRONS.ECE.TECEF:TECEF17
    - \D3D::TOP.ELECTRONS.ECE.TECEF:TECEF18
    - \D3D::TOP.ELECTRONS.ECE.TECEF:TECEF19
    - \D3D::TOP.ELECTRONS.ECE.TECEF:TECEF20
    - \D3D::TOP.ELECTRONS.ECE.TECEF:TECEF21
    - \D3D::TOP.ELECTRONS.ECE.TECEF:TECEF22
    - \D3D::TOP.ELECTRONS.ECE.TECEF:TECEF23
    - \D3D::TOP.ELECTRONS.ECE.TECEF:TECEF24
    - \D3D::TOP.ELECTRONS.ECE.TECEF:TECEF25
    - \D3D::TOP.ELECTRONS.ECE.TECEF:TECEF26
    - \D3D::TOP.ELECTRONS.ECE.TECEF:TECEF27
    - \D3D::TOP.ELECTRONS.ECE.TECEF:TECEF28
    - \D3D::TOP.ELECTRONS.ECE.TECEF:TECEF29
    - \D3D::TOP.ELECTRONS.ECE.TECEF:TECEF30
    - \D3D::TOP.ELECTRONS.ECE.TECEF:TECEF31
    - \D3D::TOP.ELECTRONS.ECE.TECEF:TECEF32
    - \D3D::TOP.ELECTRONS.ECE.TECEF:TECEF33
    - \D3D::TOP.ELECTRONS.ECE.TECEF:TECEF34
    - \D3D::TOP.ELECTRONS.ECE.TECEF:TECEF35
    - \D3D::TOP.ELECTRONS.ECE.TECEF:TECEF36
    - \D3D::TOP.ELECTRONS.ECE.TECEF:TECEF37
    - \D3D::TOP.ELECTRONS.ECE.TECEF:TECEF38
    - \D3D::TOP.ELECTRONS.ECE.TECEF:TECEF39
    - \D3D::TOP.ELECTRONS.ECE.TECEF:TECEF40
    - \D3D::TOP.ELECTRONS.ECE.TECEF:TECEF41
    - \D3D::TOP.ELECTRONS.ECE.TECEF:TECEF42
    - \D3D::TOP.ELECTRONS.ECE.TECEF:TECEF43
    - \D3D::TOP.ELECTRONS.ECE.TECEF:TECEF44
    - \D3D::TOP.ELECTRONS.ECE.TECEF:TECEF45
    - \D3D::TOP.ELECTRONS.ECE.TECEF:TECEF46
    - \D3D::TOP.ELECTRONS.ECE.TECEF:TECEF47
    - \D3D::TOP.ELECTRONS.ECE.TECEF:TECEF48

server: atlas.gat.com
