"""LaTeX tables of the ELM reference swap, in the layout of the AE benchmark tables.

`write` turns the record of `scripts/labeler/elm_reference_swap.py` into
`table_elm_benchmark.tex` (AUROC and F1 of each method against the review and against
the legacy table, as `table_ae_benchmark.tex`), `table_elm_swap_full.tex` (precision,
recall and F1 against both, with the legacy table and the expert labels as rows, as
`table_reference_swap_full.tex`), and one benchmark table per extra set. Every cell is
read from the record; none is typed.
"""

from __future__ import annotations

import math
from pathlib import Path

from . import compare

DOMAIN_NOTE = (
    "The DSM and legacy onset table were built on WPQH phases with "
    "breakthrough-ELM targets; Finding 1 and low DSM AUROCs partly reflect "
    "definition and domain shift (192721: 1 legacy bin versus 17 non-crowd "
    "review spans)."
)

NAME = compare.NAME
ROWS = (
    (NAME["ours"], "elm-ours"),
    (NAME["elmo"], "ELM-O"),
    (NAME["detect"], "elm-dsm detection"),
    (NAME["clock"], "elm-clock"),
    (NAME["dsm"], "elm-dsm refit"),
    ("elm-dsm-detect-exposed", "elm-dsm detection exposed"),
    (NAME["init"], "elm-dsm detection init"),
)
ALWAYS = "always present"
EXPOSED = {NAME["dsm"], NAME["init"], "elm-dsm-detect-exposed"}


def method_label(key: str) -> str:
    """Keep source exposure visible wherever a method's result is displayed."""
    label = dict(ROWS).get(key, key)
    if key in EXPOSED:
        label += r"$^{\ddagger}$"
    return label


def exposure_heading(columns: int) -> str:
    return (
        r"\midrule\multicolumn{"
        + str(columns)
        + r"}{l}{\emph{Supplemental: DSM source exposure$^{\ddagger}$}} \\"
    )


def cell(point: float, ci, digits=3, ci_digits=2) -> str:
    if math.isnan(point):
        return "--"
    out = f"{point:.{digits}f}"
    if ci is not None and not math.isnan(ci[0]):
        out += f" {{\\scriptsize[{ci[0]:.{ci_digits}f}, {ci[1]:.{ci_digits}f}]}}"
    return out


def metric_cell(res: dict, metric: str) -> str:
    if metric not in res["point"]:
        return "--"
    out = cell(res["point"][metric], res.get("ci95", {}).get(metric))
    if metric == "f1" and res["point"].get("recall", 0) >= 0.99:
        out += r"$^{\dagger}$"
    return out


def f1_with_pr(res: dict) -> str:
    """Numerical F1 and interval, with precision/recall beneath when available."""
    out = metric_cell(res, "f1")
    p = res["point"]
    if "precision" in p and "recall" in p:
        out = (
            r"\shortstack{"
            + out
            + r"\\{\scriptsize "
            + f"P={p['precision']:.3f}, R={p['recall']:.3f}"
            + "}}"
        )
    return out


def header(record: dict, source: str) -> str:
    return (
        f"% generated by labeler.elm.swap_tex from {source}"
        f" (git {record['git']}); do not edit\n"
    )


def benchmark_table(res: dict, ref_a: str, ref_b: str, labels, record, source) -> str:
    """`res[ref_a]` and `res[ref_b]` are `score_reference` outputs."""
    a, b = res[ref_a], res[ref_b]
    lines = [
        header(record, source) + "\\begin{tabular}{lcccc}",
        "\\toprule",
        (
            f"& \\multicolumn{{2}}{{c}}{{{labels[0]} "
            f"({100 * a['prevalence']:.0f}\\% present)}} "
            f"& \\multicolumn{{2}}{{c}}{{{labels[1]} "
            f"({100 * b['prevalence']:.0f}\\% present)}} \\\\"
        ),
        "\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}",
        "Method & AUROC & F1 & AUROC & F1 \\\\",
        "\\midrule",
    ]
    exposed = False
    for key, _ in ROWS:
        if key not in a["methods"]:
            continue
        ra, rb = a["methods"][key], b["methods"][key]
        if key in EXPOSED and not exposed:
            lines.append(exposure_heading(5))
            exposed = True
        label = method_label(key)
        lines.append(
            f"{label} & {metric_cell(ra, 'auroc')} & {metric_cell(ra, 'f1')} & "
            f"{metric_cell(rb, 'auroc')} & {metric_cell(rb, 'f1')} \\\\"
        )
    lines.append("\\midrule")
    ra, rb = a["methods"][ALWAYS], b["methods"][ALWAYS]
    lines.append(
        f"{ALWAYS} & {ra['point']['auroc']:.3f} & {metric_cell(ra, 'f1')} & "
        f"{rb['point']['auroc']:.3f} & {metric_cell(rb, 'f1')} \\\\"
    )
    lines += ["\\bottomrule", "\\end{tabular}", ""]
    return "\n".join(lines)


def prf(res: dict) -> str:
    p = res["point"]
    return f"{p['precision']:.3f} & {p['recall']:.3f} & {metric_cell(res, 'f1')}"


def main_table(res: dict, record: dict, source: str) -> str:
    """Reviewed/onset AUROC and numerical F1; companions retain P/R and gaps."""
    return benchmark_table(
        res,
        "reviewed",
        "legacy",
        ("Reviewed occupancy", "Legacy onset bins"),
        record,
        source,
    )


def full_table(res: dict, record: dict, source: str, legacy_label=None) -> str:
    a, b = res["reviewed"], res["legacy"]
    f1 = res["finding_1"]
    leg_vs_rev = f1["as_methods"]["legacy_table_vs_reviewed"]
    legacy_label = legacy_label or "legacy onset table"
    lines = [
        header(record, source) + "\\begin{tabular}{lcccccc}",
        "\\toprule",
        (
            "& \\multicolumn{3}{c}{Reference: expert dense labels} & "
            f"\\multicolumn{{3}}{{c}}{{Reference: {legacy_label}}} \\\\"
        ),
        "\\cmidrule(lr){2-4}\\cmidrule(lr){5-7}",
        "Method & P & R & F1 & P & R & F1 \\\\",
        "\\midrule",
    ]
    exposed = False
    for key, _ in ROWS:
        if key in a["methods"]:
            if key in EXPOSED and not exposed:
                lines.append(exposure_heading(7))
                exposed = True
            label = method_label(key)
            lines.append(
                f"{label} & {prf(a['methods'][key])} & {prf(b['methods'][key])} \\\\"
            )
    lines.append("\\midrule")
    lp = leg_vs_rev["point"]
    identity = r"1.000 {\scriptsize[1.00, 1.00]}$^{\dagger}$"
    lines.append(
        f"{legacy_label} & {prf(leg_vs_rev)} & 1.000 & 1.000 & {identity} \\\\"
    )
    lines.append(
        f"{ALWAYS} & {prf(a['methods'][ALWAYS])} & {prf(b['methods'][ALWAYS])} \\\\"
    )
    # the expert labels read as a detector of the legacy marks: the legacy table's
    # precision against the review is the expert's recall against the legacy table
    oracle_f1 = cell(_f1(lp["recall"], lp["precision"]), leg_vs_rev["ci95"]["f1"], 3, 3)
    lines.append(
        f"expert (oracle) & 1.000 & 1.000 & {identity} & {lp['recall']:.3f} & "
        f"{lp['precision']:.3f} & {oracle_f1} \\\\"
    )
    lines += [
        "\\midrule",
        (
            f"Prevalence of present bins & \\multicolumn{{3}}{{c}}"
            f"{{{a['prevalence']:.3f}}} & \\multicolumn{{3}}{{c}}"
            f"{{{b['prevalence']:.3f}}} \\\\"
        ),
        (
            f"$|M|$, $|P|$ of {f1['bins']} bins & \\multicolumn{{6}}{{c}}"
            f"{{$|M|={f1['M']}$, $|P|={f1['P']}$}} \\\\"
        ),
        "\\bottomrule",
        "\\end{tabular}",
        "",
    ]
    return "\n".join(lines)


def _f1(p: float, r: float) -> float:
    return 2 * p * r / (p + r) if p + r else float("nan")


def write(
    record: dict, out_dir: Path, source="outputs/labeler/elm/swap/evaluation.json"
):
    """Four consolidated appendix tables; complete diagnostics remain in JSON."""
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    panels = []
    for tag in ("overlap", "overlap_bes"):
        res = record["swap"][tag]
        panels.append(panel_heading(res) + main_table(res, record, source))
    caption = (
        "ELM reference swap: eight overlap shots and seven with BES; evidence "
        "is inconclusive. F1 uses review-tuned thresholds; AUROC compares "
        "references. Only three source-unexposed shots and two with BES are "
        "descriptive only. Brackets show eligible shot-bootstrap intervals."
    )
    tables = {
        "table_elm_swap.tex": wrap_table(
            "\n\\medskip\n".join(panels), caption, "tab:elm-swap"
        ),
        "table_elm_swap_full.tex": wrap_table(
            full_table(record["swap"]["overlap"], record, source),
            "Fixed-prediction precision, recall and F1 against both references. "
            "Eight overlap shots; identity oracle results hold by definition. "
            "Brackets show eligible shot-bootstrap intervals; F1 is review-tuned.",
            "tab:elm-swap-full",
        ),
        "table_elm_swap_sensitivity.tex": wrap_table(
            sensitivity_table(record, source),
            "Legacy onset bins and covered-gap occupancy sensitivities. "
            "All-covered review states use at least 25 ms present occupancy. "
            "Missing coverage is never bridged. Tiny positive-shot subsets are "
            "descriptive only; eligible intervals use 1000 shot draws.",
            "tab:elm-swap-sensitivity",
        ),
        "table_elm_swap_rankings.tex": wrap_table(
            ranking_table(record, source, "auroc"),
            "AUROC point orders with fixed predictions on strict interior bins "
            "and known all-covered bins. Eight-shot evidence is inconclusive; "
            "point crossings cannot establish population ranking reversal. "
            "Source-exposed variants are supplemental.",
            "tab:elm-swap-rankings",
        ),
    }
    for name, content in tables.items():
        (out_dir / name).write_text(content)


def panel_heading(res: dict) -> str:
    if res.get("has_elmo"):
        text = f"{res['n_shots']} BES shots, ELM-O chunks"
    else:
        text = f"All {res['n_shots']} overlap shots"
    if not res.get("dsm_refit_training_shots"):
        text += "; DSM source-unexposed subset"
    return f"\\textbf{{{text}: {res['reviewed']['bins']} bins}}\\par\\smallskip\n"


def bes_point_order_crosses(record: dict) -> bool:
    """Whether clean DSM and ELM-O exchange point-AUROC order in the BES swap."""
    res = record["swap"]["overlap_bes"]
    clean, elmo = NAME["detect"], NAME["elmo"]

    def delta(reference):
        methods = reference["methods"]
        return methods[clean]["point"]["auroc"] - methods[elmo]["point"]["auroc"]

    baseline = delta(res["reviewed"])
    return any(
        baseline * delta(reference) < 0
        for reference in (
            res["legacy"],
            *(r["legacy"] for r in res["occupancy"].values()),
        )
    )


def sensitivity_table(record: dict, source: str) -> str:
    lines = [
        header(record, source) + r"\begin{tabular}{lrrrrrr}",
        r"\toprule",
        r"Legacy reference & Bins & $|M|$ & $|P|$ & P & R & F1 \\",
        r"\midrule",
    ]
    audits = [("all-covered", record["interval_audit"]["known_review_majority"])]
    for key, audit in record["interval_audit_occupancy"].items():
        audits.append((key, audit["known_review_majority"]))
    groups = [("All-covered majority (8 shots)", audits)]
    for tag, res in record["swap"].items():
        refs = [("onset", res["finding_1"])] + [
            (key, value["finding_1"]) for key, value in res["occupancy"].items()
        ]
        scope = (
            f"{res['n_shots']} BES shots, ELM-O chunks"
            if res["has_elmo"]
            else f"All {res['n_shots']} overlap shots"
        )
        if "heldout" in tag:
            scope += ", elm-dsm source held out"
        groups.append((scope, refs))
    for scope, refs in groups:
        lines.append(r"\multicolumn{7}{l}{\textbf{" + scope + r"}} \\")
        for key, result in refs:
            label = (
                "onset bins"
                if key in ("onset", "all-covered")
                else ("$\\tau=" + key.removeprefix("gap_").removesuffix("ms") + "$ ms")
            )
            p = result["point"]
            lines.append(
                f"{label} & {result['bins']} & {result['M']} & "
                f"{result['P']} & {p['precision']:.3f} & "
                f"{metric_cell(result, 'recall')} & {metric_cell(result, 'f1')} \\\\"
            )
        lines.append(r"\midrule")
    lines[-1] = r"\bottomrule"
    lines += [r"\end{tabular}", ""]
    return "\n".join(lines)


def ranking_table(record: dict, source: str, metric: str) -> str:
    lines = [
        header(record, source) + r"\begin{tabular}{lp{0.73\textwidth}}",
        r"\toprule",
        f"Reference & {metric.upper()}: methods, best first " + r"\\",
        r"\midrule",
    ]
    scopes = [
        (tag, res)
        for tag, res in record["swap"].items()
        if tag in ("overlap", "overlap_bes")
    ]
    scopes += [
        ("all-covered " + tag, res)
        for tag, res in record.get("all_covered_swap", {}).items()
    ]
    for tag, res in scopes:
        refs = [("reviewed", res["reviewed"]), ("onset bins", res["legacy"])] + [
            (f"$\\tau={r['gap_ms']}$ ms", r["legacy"])
            for r in res.get("occupancy", {}).values()
        ]
        scope = (
            f"{res['n_shots']} BES shots, ELM-O chunks"
            if res["has_elmo"]
            else f"All {res['n_shots']} overlap shots"
        )
        scope += f"; {res['reviewed']['bins']} bins"
        if tag.startswith("all-covered"):
            label = (
                "Known majority, detection coverage"
                if "detection_common" in tag
                else "Known majority, complete scores"
            )
            scope = label + ": " + scope
        lines.append(r"\multicolumn{2}{l}{\textbf{" + scope + r"}} \\")
        for name, reference in refs:
            # Historical initialization variants have their own numerical appendix.
            order = " $>$ ".join(
                method_label(n)
                for n in reference["ranking"][metric]
                if n not in (NAME["init"], "elm-dsm-detect-exposed")
            )
            lines.append(f"{name} & {order} " + r"\\")
        lines.append(r"\midrule")
    lines[-1] = r"\bottomrule"
    lines += [r"\end{tabular}", ""]
    return "\n".join(lines)


def swap_caption(res: dict, gap: int | None = None, full: bool = False) -> str:
    reference = (
        "legacy onset-bin presence"
        if gap is None
        else f"legacy occupancy with $\\tau={gap}$ ms covered gaps"
    )
    return (
        f"Reviewed occupancy versus {reference}: {res['n_shots']} shots/"
        f"{res['reviewed']['bins']} identical 50 ms interior bins. "
        + (
            "Precision, recall and numerical F1 include the reference and oracle "
            "rows; identity agreement is by definition. "
            if full
            else "AUROC and numerical F1 use identical predictions. "
        )
        + (
            "F1 retains review-tuned thresholds and is descriptive. "
            if full
            else "F1 retains review-tuned thresholds; only AUROC compares references. "
        )
        + "Brackets show shot-bootstrap intervals; $^{\\ddagger}$ marks supplemental "
        "source exposure and $^{\\dagger}$ marks recall $\\geq0.99$."
    )


def wrap_table(body: str, caption: str, label: str) -> str:
    if DOMAIN_NOTE not in caption:
        caption += " " + DOMAIN_NOTE
    return (
        "\\begin{table*}[t]\n\\centering\n\\small\n"
        + body
        + "\\caption{"
        + caption
        + "}\n\\label{"
        + label
        + "}\n"
        + "\\end{table*}\n"
    )
