"""LaTeX tables of the ELM reference swap, in the layout of the AE benchmark tables.

`write` turns the record of `scripts/labeler/elm_reference_swap.py` into
`table_elm_benchmark.tex` (AUROC and F1 of each method against the review and against
the legacy table, as `table_ae_benchmark.tex`), `table_elm_swap_full.tex` (precision,
recall and F1 against both, with the legacy table and the expert labels as rows, as
`table_reference_swap_full.tex`), and one benchmark table per extra set. Every cell is
read from the record; none is typed.
"""

from __future__ import annotations

import math
from pathlib import Path

from . import compare

NAME = compare.NAME
ROWS = (
    (NAME["ours"], "elm-ours"),
    (NAME["elmo"], "ELM-O"),
    (
        NAME["dsm"],
        r"\shortstack[l]{DSM refit, limited inputs\\(60 of the original 124)}",
    ),
    (
        NAME["detect"],
        r"\shortstack[l]{DSM refit, limited inputs\\(60 of the original 124), detection}",
    ),
    (
        NAME["init"],
        r"\shortstack[l]{DSM refit, limited inputs\\(60 of the original 124), detection init}",
    ),
    (NAME["clock"], "elm-clock"),
)
ALWAYS = "always present"


def cell(point: float, ci, digits=3, ci_digits=2) -> str:
    if math.isnan(point):
        return "--"
    out = f"{point:.{digits}f}"
    if ci is not None and not math.isnan(ci[0]):
        out += f" {{\\scriptsize[{ci[0]:.{ci_digits}f}, {ci[1]:.{ci_digits}f}]}}"
    return out


def metric_cell(res: dict, metric: str) -> str:
    if metric not in res["point"]:
        return "--"
    if metric == "f1" and res["point"].get("recall", 0) >= 0.99:
        return r"\textit{degenerate}"
    return cell(res["point"][metric], res.get("ci95", {}).get(metric))


def header(record: dict, source: str) -> str:
    return (
        f"% generated by labeler.elm.swap_tex from {source}"
        f" (git {record['git']}); do not edit\n"
    )


def benchmark_table(res: dict, ref_a: str, ref_b: str, labels, record, source) -> str:
    """`res[ref_a]` and `res[ref_b]` are `score_reference` outputs."""
    a, b = res[ref_a], res[ref_b]
    lines = [
        header(record, source) + "\\begin{tabular}{lcccc}",
        "\\toprule",
        (
            f"& \\multicolumn{{2}}{{c}}{{{labels[0]} "
            f"({100 * a['prevalence']:.0f}\\% present)}} "
            f"& \\multicolumn{{2}}{{c}}{{{labels[1]} "
            f"({100 * b['prevalence']:.0f}\\% present)}} \\\\"
        ),
        "\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}",
        "Method & AUROC & F1 & AUROC & F1 \\\\",
        "\\midrule",
    ]
    for key, label in ROWS:
        if key not in a["methods"]:
            continue
        ra, rb = a["methods"][key], b["methods"][key]
        lines.append(
            f"{label} & {metric_cell(ra, 'auroc')} & {metric_cell(ra, 'f1')} & "
            f"{metric_cell(rb, 'auroc')} & {metric_cell(rb, 'f1')} \\\\"
        )
    lines.append("\\midrule")
    ra, rb = a["methods"][ALWAYS], b["methods"][ALWAYS]
    lines.append(
        f"{ALWAYS} & {ra['point']['auroc']:.3f} & {metric_cell(ra, 'f1')} & "
        f"{rb['point']['auroc']:.3f} & {metric_cell(rb, 'f1')} \\\\"
    )
    lines += ["\\bottomrule", "\\end{tabular}", ""]
    return "\n".join(lines)


def prf(res: dict) -> str:
    p = res["point"]
    return f"{p['precision']:.3f} & {p['recall']:.3f} & {metric_cell(res, 'f1')}"


def full_table(res: dict, record: dict, source: str) -> str:
    a, b = res["reviewed"], res["legacy"]
    f1 = res["finding_1"]
    leg_vs_rev = f1["as_methods"]["legacy_table_vs_reviewed"]
    lines = [
        header(record, source) + "\\begin{tabular}{lcccccc}",
        "\\toprule",
        (
            "& \\multicolumn{3}{c}{Reference: expert dense labels} & "
            "\\multicolumn{3}{c}{Reference: legacy onset table} \\\\"
        ),
        "\\cmidrule(lr){2-4}\\cmidrule(lr){5-7}",
        "Method & P & R & F1 & P & R & F1 \\\\",
        "\\midrule",
    ]
    for key, label in ROWS:
        if key in a["methods"]:
            lines.append(
                f"{label} & {prf(a['methods'][key])} & {prf(b['methods'][key])} \\\\"
            )
    lines.append("\\midrule")
    lp = leg_vs_rev["point"]
    lines.append(f"legacy onset table & {prf(leg_vs_rev)} & 1.000 & 1.000 & 1.000 \\\\")
    lines.append(
        f"{ALWAYS} & {prf(a['methods'][ALWAYS])} & {prf(b['methods'][ALWAYS])} \\\\"
    )
    # the expert labels read as a detector of the legacy marks: the legacy table's
    # precision against the review is the expert's recall against the legacy table
    oracle_f1 = cell(_f1(lp["recall"], lp["precision"]), leg_vs_rev["ci95"]["f1"], 3, 3)
    lines.append(
        f"expert (oracle) & 1.000 & 1.000 & 1.000 & {lp['recall']:.3f} & "
        f"{lp['precision']:.3f} & {oracle_f1} \\\\"
    )
    lines += [
        "\\midrule",
        (
            f"Prevalence of present bins & \\multicolumn{{3}}{{c}}"
            f"{{{a['prevalence']:.3f}}} & \\multicolumn{{3}}{{c}}"
            f"{{{b['prevalence']:.3f}}} \\\\"
        ),
        (
            f"$|M|$, $|P|$ of {f1['bins']} bins & \\multicolumn{{6}}{{c}}"
            f"{{$|M|={f1['M']}$, $|P|={f1['P']}$}} \\\\"
        ),
        "\\bottomrule",
        "\\end{tabular}",
        "",
    ]
    return "\n".join(lines)


def _f1(p: float, r: float) -> float:
    return 2 * p * r / (p + r) if p + r else float("nan")


def write(
    record: dict, out_dir: Path, source="outputs/labeler/elm/swap/evaluation.json"
):
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    labels = ("dense labels", "legacy onset table")
    for tag, name in (
        ("overlap", "table_elm_swap_all.tex"),
        ("overlap_bes", "table_elm_swap_bes.tex"),
    ):
        res = record["swap"].get(tag)
        if not res or "finding_1" not in res:
            continue
        caption = swap_caption(res)
        (out_dir / name).write_text(
            wrap_table(
                benchmark_table(res, "reviewed", "legacy", labels, record, source),
                caption,
                f"tab:elm-swap-{tag}",
            )
        )
        if tag == "overlap":
            (out_dir / "table_elm_swap_full.tex").write_text(
                wrap_table(
                    full_table(res, record, source),
                    caption
                    + " Identity-reference rows show exact agreement by definition.",
                    "tab:elm-swap-full",
                )
            )
    for tag, res in record["proxy"].items():
        text = benchmark_table(
            res,
            "reviewed",
            "proxy",
            ("dense labels", res["label"]),
            record,
            source,
        )
        caption = (
            f"Detector-derived proxy comparison: {res['shots']} shots, "
            f"{res['reviewed']['bins']} identical 50 ms interior bins with DSM rows. "
            "The producer is excluded; the proxy is not an independent reference. "
            + interval_caption()
        )
        (out_dir / f"table_elm_proxy_{tag}.tex").write_text(
            wrap_table(text, caption, f"tab:elm-proxy-{tag}")
        )
    panels = []
    descriptions = []
    for tag in ("overlap", "overlap_bes"):
        res = record["swap"][tag]
        panels.append(
            benchmark_table(res, "reviewed", "legacy", labels, record, source)
        )
        descriptions.append(
            f"{'All overlap' if tag == 'overlap' else 'BES subset'}: "
            f"{res['n_shots']} shots/{res['reviewed']['bins']} bins"
        )
    audit = record["interval_audit"]
    full = audit["known_review_majority"]
    uncertain = audit["excluded_review_states"]["uncertain"]
    caption = (
        "ELM reference swap, " + "; ".join(descriptions) + ". "
        "Identical predictions and thresholds under reviewed interval occupancy "
        "and legacy onset-bin presence; bins lie wholly inside one known review "
        "span and analysed time with DSM rows. This restriction deviates from "
        "the AE audit. All-covered majority audit: "
        f"{audit['legacy_covered_bins']} bins, {full['bins']} known-review bins, "
        f"$|M|={full['M']}$, $|P|={full['P']}$; "
        f"{uncertain['bins']} review-uncertain bins "
        f"({uncertain['legacy_present_bins']} legacy-positive), reported separately. "
        f"{audit['excluded_review_states']['mixed_or_unlabelled']['bins']} "
        "mixed-review bins "
        "are also excluded from known-review counts. "
        "M/P measure occupancy/onset-bin disagreement, not verified omitted ELMs. "
        + interval_caption()
    )
    (out_dir / "table_elm_swap.tex").write_text(
        wrap_table("\n\\medskip\n".join(panels), caption, "tab:elm-swap")
    )


def interval_caption() -> str:
    return (
        "Brackets are 95\\% percentile intervals from 1,000 shot-bootstrap "
        "resamples, shared across methods and references. ELM-O AUROC uses the "
        "saved nested eta sweep on these exact bins; the clock has hard calls only. "
        "DSM refit, limited inputs (60 of the original 124), was trained on "
        "Hiro's legacy onset source with reviewed and cohort-test shot overlap; "
        "detection heads "
        "use reviewed spans, with the initialized variant retaining that embedding. "
        "Detector/rule F1 is marked degenerate when recall $\\geq0.99$."
    )


def swap_caption(res: dict) -> str:
    return (
        f"ELM reference swap: {res['n_shots']} shots/{res['reviewed']['bins']} "
        "identical 50 ms bins wholly inside known review spans and analysed time, "
        "with DSM rows. Reviewed interval occupancy differs from legacy onset-bin "
        "presence; this restriction deviates from the AE all-frame audit. "
        + interval_caption()
    )


def wrap_table(body: str, caption: str, label: str) -> str:
    return (
        "\\begin{table*}[t]\n\\centering\n\\small\n"
        + body
        + "\\caption{"
        + caption
        + "}\n\\label{"
        + label
        + "}\n"
        + "\\end{table*}\n"
    )
