"""LaTeX tables of the ELM reference swap, in the layout of the AE benchmark tables.

`write` turns the record of `scripts/labeler/elm_reference_swap.py` into
`table_elm_benchmark.tex` (AUROC and F1 of each method against the review and against
the legacy table, as `table_ae_benchmark.tex`), `table_elm_swap_full.tex` (precision,
recall and F1 against both, with the legacy table and the expert labels as rows, as
`table_reference_swap_full.tex`), and one benchmark table per extra set. Every cell is
read from the record; none is typed.
"""

from __future__ import annotations

import math
from pathlib import Path

from . import compare

NAME = compare.NAME
ROWS = (
    (NAME["ours"], "elm-ours"),
    (NAME["elmo"], "ELM-O"),
    (NAME["dsm"], "elm-dsm refit"),
    (NAME["detect"], "elm-dsm detection"),
    (NAME["init"], "elm-dsm detection init"),
    (NAME["clock"], "elm-clock"),
)
ALWAYS = "always present"


def cell(point: float, ci, digits=3, ci_digits=2) -> str:
    if math.isnan(point):
        return "--"
    out = f"{point:.{digits}f}"
    if ci is not None and not math.isnan(ci[0]):
        out += f" {{\\scriptsize[{ci[0]:.{ci_digits}f}, {ci[1]:.{ci_digits}f}]}}"
    return out


def metric_cell(res: dict, metric: str) -> str:
    if metric not in res["point"]:
        return "--"
    out = cell(res["point"][metric], res.get("ci95", {}).get(metric))
    if metric == "f1" and res["point"].get("recall", 0) >= 0.99:
        out += r"$^{\dagger}$"
    return out


def f1_with_pr(res: dict) -> str:
    """Numerical F1 and interval, with precision/recall beneath when available."""
    out = metric_cell(res, "f1")
    p = res["point"]
    if "precision" in p and "recall" in p:
        out = (
            r"\shortstack{"
            + out
            + r"\\{\scriptsize "
            + f"P={p['precision']:.3f}, R={p['recall']:.3f}"
            + "}}"
        )
    return out


def header(record: dict, source: str) -> str:
    return (
        f"% generated by labeler.elm.swap_tex from {source}"
        f" (git {record['git']}); do not edit\n"
    )


def benchmark_table(res: dict, ref_a: str, ref_b: str, labels, record, source) -> str:
    """`res[ref_a]` and `res[ref_b]` are `score_reference` outputs."""
    a, b = res[ref_a], res[ref_b]
    lines = [
        header(record, source) + "\\begin{tabular}{lcccc}",
        "\\toprule",
        (
            f"& \\multicolumn{{2}}{{c}}{{{labels[0]} "
            f"({100 * a['prevalence']:.0f}\\% present)}} "
            f"& \\multicolumn{{2}}{{c}}{{{labels[1]} "
            f"({100 * b['prevalence']:.0f}\\% present)}} \\\\"
        ),
        "\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}",
        "Method & AUROC & F1 & AUROC & F1 \\\\",
        "\\midrule",
    ]
    for key, label in ROWS:
        if key not in a["methods"]:
            continue
        ra, rb = a["methods"][key], b["methods"][key]
        if key in (NAME["dsm"], NAME["init"]) and res.get("dsm_refit_training_shots"):
            label += r"$^{\ddagger}$"
        lines.append(
            f"{label} & {metric_cell(ra, 'auroc')} & {f1_with_pr(ra)} & "
            f"{metric_cell(rb, 'auroc')} & {f1_with_pr(rb)} \\\\"
        )
    lines.append("\\midrule")
    ra, rb = a["methods"][ALWAYS], b["methods"][ALWAYS]
    lines.append(
        f"{ALWAYS} & {ra['point']['auroc']:.3f} & {f1_with_pr(ra)} & "
        f"{rb['point']['auroc']:.3f} & {f1_with_pr(rb)} \\\\"
    )
    lines += ["\\bottomrule", "\\end{tabular}", ""]
    return "\n".join(lines)


def prf(res: dict) -> str:
    p = res["point"]
    return f"{p['precision']:.3f} & {p['recall']:.3f} & {metric_cell(res, 'f1')}"


def main_table(res: dict, record: dict, source: str) -> str:
    """Reviewed, onset and 200 ms occupancy metrics on the same bins."""
    refs = [res["reviewed"], res["legacy"], res["occupancy"]["gap_200ms"]["legacy"]]
    lines = [
        header(record, source) + r"\setlength{\tabcolsep}{1.5pt}",
        r"\begin{tabular}{lcccccc}",
        r"\toprule",
        (
            r"& \multicolumn{2}{c}{Reviewed occupancy} & "
            r"\multicolumn{2}{c}{Legacy onset bins} & "
            r"\multicolumn{2}{c}{Legacy occupancy ($\tau=200$ ms)} \\"
        ),
        r"\cmidrule(lr){2-3}\cmidrule(lr){4-5}\cmidrule(lr){6-7}",
        r"Method & AUROC & F1 & AUROC & F1 & AUROC & F1 \\",
        r"\midrule",
    ]
    for key, label in (*ROWS, (ALWAYS, ALWAYS)):
        if key not in refs[0]["methods"]:
            continue
        if key == ALWAYS:
            lines.append(r"\midrule")
        if key in (NAME["dsm"], NAME["init"]) and res.get("dsm_refit_training_shots"):
            label += r"$^{\ddagger}$"
        values = []
        for reference in refs:
            result = reference["methods"][key]
            values.append(metric_cell(result, "auroc"))
            values.append(
                f1_with_pr(result)
                if result["point"]["recall"] >= 0.99
                else metric_cell(result, "f1")
            )
        lines.append(label + " & " + " & ".join(values) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}", ""]
    return "\n".join(lines)


def full_table(res: dict, record: dict, source: str, legacy_label=None) -> str:
    a, b = res["reviewed"], res["legacy"]
    f1 = res["finding_1"]
    leg_vs_rev = f1["as_methods"]["legacy_table_vs_reviewed"]
    legacy_label = legacy_label or "legacy onset table"
    lines = [
        header(record, source) + "\\begin{tabular}{lcccccc}",
        "\\toprule",
        (
            "& \\multicolumn{3}{c}{Reference: expert dense labels} & "
            f"\\multicolumn{{3}}{{c}}{{Reference: {legacy_label}}} \\\\"
        ),
        "\\cmidrule(lr){2-4}\\cmidrule(lr){5-7}",
        "Method & P & R & F1 & P & R & F1 \\\\",
        "\\midrule",
    ]
    for key, label in ROWS:
        if key in a["methods"]:
            if key in (NAME["dsm"], NAME["init"]) and res.get(
                "dsm_refit_training_shots"
            ):
                label += r"$^{\ddagger}$"
            lines.append(
                f"{label} & {prf(a['methods'][key])} & {prf(b['methods'][key])} \\\\"
            )
    lines.append("\\midrule")
    lp = leg_vs_rev["point"]
    identity = r"1.000 {\scriptsize[1.00, 1.00]}$^{\dagger}$"
    lines.append(
        f"{legacy_label} & {prf(leg_vs_rev)} & 1.000 & 1.000 & {identity} \\\\"
    )
    lines.append(
        f"{ALWAYS} & {prf(a['methods'][ALWAYS])} & {prf(b['methods'][ALWAYS])} \\\\"
    )
    # the expert labels read as a detector of the legacy marks: the legacy table's
    # precision against the review is the expert's recall against the legacy table
    oracle_f1 = cell(_f1(lp["recall"], lp["precision"]), leg_vs_rev["ci95"]["f1"], 3, 3)
    lines.append(
        f"expert (oracle) & 1.000 & 1.000 & {identity} & {lp['recall']:.3f} & "
        f"{lp['precision']:.3f} & {oracle_f1} \\\\"
    )
    lines += [
        "\\midrule",
        (
            f"Prevalence of present bins & \\multicolumn{{3}}{{c}}"
            f"{{{a['prevalence']:.3f}}} & \\multicolumn{{3}}{{c}}"
            f"{{{b['prevalence']:.3f}}} \\\\"
        ),
        (
            f"$|M|$, $|P|$ of {f1['bins']} bins & \\multicolumn{{6}}{{c}}"
            f"{{$|M|={f1['M']}$, $|P|={f1['P']}$}} \\\\"
        ),
        "\\bottomrule",
        "\\end{tabular}",
        "",
    ]
    return "\n".join(lines)


def _f1(p: float, r: float) -> float:
    return 2 * p * r / (p + r) if p + r else float("nan")


def write(
    record: dict, out_dir: Path, source="outputs/labeler/elm/swap/evaluation.json"
):
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    labels = ("dense labels", "legacy onset table")
    for tag, name in (
        ("overlap", "table_elm_swap_all.tex"),
        ("overlap_bes", "table_elm_swap_bes.tex"),
        ("overlap_dsm_heldout", "table_elm_swap_dsm_heldout.tex"),
        ("overlap_bes_dsm_heldout", "table_elm_swap_bes_dsm_heldout.tex"),
    ):
        res = record["swap"].get(tag)
        if not res or "finding_1" not in res:
            continue
        caption = swap_caption(res)
        (out_dir / name).write_text(
            wrap_table(
                panel_heading(res)
                + benchmark_table(res, "reviewed", "legacy", labels, record, source),
                caption,
                f"tab:elm-swap-{tag}",
            )
        )
        if tag == "overlap":
            (out_dir / "table_elm_swap_full.tex").write_text(
                wrap_table(
                    full_table(res, record, source),
                    caption
                    + " Identity-reference rows show exact agreement by definition.",
                    "tab:elm-swap-full",
                )
            )
        for converted in res.get("occupancy", {}).values():
            merged = {**res, **converted}
            gap = converted["gap_ms"]
            label = f"legacy occupancy, $\\tau={gap}$ ms"
            (out_dir / f"table_elm_swap_{tag}_occupancy_{gap}ms.tex").write_text(
                wrap_table(
                    panel_heading(res)
                    + benchmark_table(
                        merged, "reviewed", "legacy", (labels[0], label), record, source
                    ),
                    swap_caption(res) + occupancy_caption(gap),
                    f"tab:elm-swap-{tag}-occupancy-{gap}ms",
                )
            )
            if tag == "overlap":
                (out_dir / f"table_elm_swap_full_occupancy_{gap}ms.tex").write_text(
                    wrap_table(
                        full_table(merged, record, source, label),
                        swap_caption(res)
                        + occupancy_caption(gap)
                        + " Identity-reference rows agree by definition.",
                        f"tab:elm-swap-full-occupancy-{gap}ms",
                    )
                )
    for tag, res in record["proxy"].items():
        text = benchmark_table(
            res,
            "reviewed",
            "proxy",
            ("dense labels", res["label"]),
            record,
            source,
        )
        caption = (
            f"Detector-derived proxy comparison: {res['shots']} shots, "
            f"{res['reviewed']['bins']} identical 50 ms interior bins with DSM rows. "
            "The producer is excluded; the proxy is not an independent reference. "
            + interval_caption()
        )
        (out_dir / f"table_elm_proxy_{tag}.tex").write_text(
            wrap_table(text, caption, f"tab:elm-proxy-{tag}")
        )
    panels = []
    descriptions = []
    for tag in ("overlap", "overlap_bes"):
        res = record["swap"][tag]
        panels.append(panel_heading(res) + main_table(res, record, source))
        descriptions.append(
            f"{'All overlap' if tag == 'overlap' else 'BES subset, ELM-O chunks'}: "
            f"{res['n_shots']} shots/{res['reviewed']['bins']} bins"
        )
    audit = record["interval_audit"]
    full = audit["known_review_majority"]
    uncertain = audit["excluded_review_states"]["uncertain"]
    caption = (
        "ELM reference swap, " + "; ".join(descriptions) + ". "
        "Identical predictions and thresholds under reviewed interval occupancy "
        "and legacy onset-bin presence or 200 ms-gap occupancy; bins lie wholly "
        "inside one known review "
        "span and analysed time with DSM rows. This restriction deviates from "
        "the AE audit. All-covered majority audit: "
        f"{audit['legacy_covered_bins']} bins, {full['bins']} known-review bins, "
        f"$|M|={full['M']}$, $|P|={full['P']}$; "
        f"{uncertain['bins']} review-uncertain bins "
        f"({uncertain['legacy_present_bins']} legacy-positive), reported separately. "
        f"{audit['excluded_review_states']['mixed_or_unlabelled']['bins']} "
        "mixed-review bins "
        "are also excluded from known-review counts. "
        "M/P measure occupancy/onset-bin disagreement, not verified omitted ELMs. "
        "The occupancy sensitivity table reports covered-gap thresholds "
        "$\\tau=100,200,300$ ms alongside the original onset bins. "
        "Companion full tables give precision and recall for every row. "
        + dsm_scope_caption(record["swap"]["overlap"])
        + interval_caption()
    )
    (out_dir / "table_elm_swap.tex").write_text(
        wrap_table("\n\\medskip\n".join(panels), caption, "tab:elm-swap")
    )
    for gap in (100, 200, 300):
        panels = []
        for tag in ("overlap", "overlap_bes"):
            res = record["swap"][tag]
            merged = {**res, **res["occupancy"][f"gap_{gap}ms"]}
            panels.append(
                panel_heading(res)
                + benchmark_table(
                    merged,
                    "reviewed",
                    "legacy",
                    (labels[0], f"legacy occupancy, $\\tau={gap}$ ms"),
                    record,
                    source,
                )
            )
        (out_dir / f"table_elm_swap_occupancy_{gap}ms.tex").write_text(
            wrap_table(
                "\n\\medskip\n".join(panels),
                swap_caption(record["swap"]["overlap"]) + occupancy_caption(gap),
                f"tab:elm-swap-occupancy-{gap}ms",
            )
        )
    (out_dir / "table_elm_swap_sensitivity.tex").write_text(
        wrap_table(
            sensitivity_table(record, source),
            "Legacy-reference occupancy sensitivity, beside the original onset-bin "
            "reference. All-covered counts use >=25 ms majority occupancy; strict "
            "sets use identical benchmark bins. $|M|$ and $|P|$ are disagreement "
            "counts against the reviewed occupancy. Positive legacy intervals "
            "merge across covered gaps of at most $\\tau$; missing legacy coverage "
            "is never bridged and no threshold is selected again. "
            + interval_caption(),
            "tab:elm-swap-sensitivity",
        )
    )
    ranking_tables = []
    for metric in ("auroc", "f1"):
        text = wrap_table(
            ranking_table(record, source, metric),
            f"{metric.upper()} point-metric rankings under reviewed occupancy, "
            "original legacy onset bins and all occupancy sensitivities on identical "
            "bins. No method predictions or thresholds change. The always-present "
            "control is included in metric tables and omitted from these detector "
            "rankings. "
            + dsm_scope_caption(record["swap"]["overlap"])
            + interval_caption(),
            f"tab:elm-swap-rankings-{metric}",
        )
        ranking_tables.append(text)
        (out_dir / f"table_elm_swap_rankings_{metric}.tex").write_text(text)
    (out_dir / "table_elm_swap_rankings.tex").write_text("\n".join(ranking_tables))


def panel_heading(res: dict) -> str:
    if res.get("has_elmo"):
        text = f"{res['n_shots']} BES shots, ELM-O chunks"
    else:
        text = f"All {res['n_shots']} overlap shots"
    if not res.get("dsm_refit_training_shots"):
        text += "; outside original DSM fitting/selection sets"
    return f"\\textbf{{{text}: {res['reviewed']['bins']} bins}}\\par\\smallskip\n"


def sensitivity_table(record: dict, source: str) -> str:
    lines = [
        header(record, source) + r"\begin{tabular}{lrrrrrr}",
        r"\toprule",
        r"Legacy reference & Bins & $|M|$ & $|P|$ & P & R & F1 \\",
        r"\midrule",
    ]
    audits = [("all-covered", record["interval_audit"]["known_review_majority"])]
    for key, audit in record["interval_audit_occupancy"].items():
        audits.append((key, audit["known_review_majority"]))
    groups = [("All-covered majority (8 shots)", audits)]
    for tag, res in record["swap"].items():
        refs = [("onset", res["finding_1"])] + [
            (key, value["finding_1"]) for key, value in res["occupancy"].items()
        ]
        scope = (
            f"{res['n_shots']} BES shots, ELM-O chunks"
            if res["has_elmo"]
            else f"All {res['n_shots']} overlap shots"
        )
        if "heldout" in tag:
            scope += ", elm-dsm source held out"
        groups.append((scope, refs))
    for scope, refs in groups:
        lines.append(r"\multicolumn{7}{l}{\textbf{" + scope + r"}} \\")
        for key, result in refs:
            label = (
                "onset bins"
                if key in ("onset", "all-covered")
                else ("$\\tau=" + key.removeprefix("gap_").removesuffix("ms") + "$ ms")
            )
            p = result["point"]
            lines.append(
                f"{label} & {result['bins']} & {result['M']} & "
                f"{result['P']} & {p['precision']:.3f} & "
                f"{metric_cell(result, 'recall')} & {metric_cell(result, 'f1')} \\\\"
            )
        lines.append(r"\midrule")
    lines[-1] = r"\bottomrule"
    lines += [r"\end{tabular}", ""]
    return "\n".join(lines)


def ranking_table(record: dict, source: str, metric: str) -> str:
    display_names = dict(ROWS)
    lines = [
        header(record, source) + r"\begin{tabular}{lp{0.74\textwidth}}",
        r"\toprule",
        f"Reference & {metric.upper()}: methods, best first " + r"\\",
        r"\midrule",
    ]
    for tag in ("overlap", "overlap_bes"):
        res = record["swap"][tag]
        refs = [("reviewed", res["reviewed"]), ("onset bins", res["legacy"])] + [
            (f"$\\tau={r['gap_ms']}$ ms", r["legacy"])
            for r in res["occupancy"].values()
        ]
        scope = (
            f"{res['n_shots']} BES shots, ELM-O chunks"
            if res["has_elmo"]
            else f"All {res['n_shots']} overlap shots"
        )
        lines.append(r"\multicolumn{2}{l}{\textbf{" + scope + r"}} \\")
        for name, reference in refs:
            order = " $>$ ".join(display_names[n] for n in reference["ranking"][metric])
            lines.append(f"{name} & {order} " + r"\\")
        lines.append(r"\midrule")
    lines[-1] = r"\bottomrule"
    lines += [r"\end{tabular}", ""]
    return "\n".join(lines)


def occupancy_caption(gap: int) -> str:
    return (
        f" Occupancy conversion merges legacy positive intervals separated by "
        f"covered gaps $\\leq{gap}$ ms; missing coverage is never bridged. "
        "The original onset bins and all three gap sensitivities are retained; "
        "predictions and thresholds are identical under every reference."
    )


def dsm_scope_caption(res: dict) -> str:
    trained = res.get("dsm_refit_training_shots", [])
    if trained:
        return (
            "$^{\\ddagger}$ In-sample original-refit exposure on "
            + ", ".join(map(str, trained))
            + "; detection init retains this embedding. "
            "Separate rows report the three shots outside original fitting and "
            "early-stopping sets (189885, 192732, 200385). "
        )
    return (
        "These shots lie outside the original DSM fitting and early-stopping "
        "sets; upstream normalization exposure remains. "
    )


def interval_caption() -> str:
    return (
        "Brackets are 95\\% percentile intervals from 1,000 shot-bootstrap "
        "resamples, shared across methods and references. ELM-O AUROC uses the "
        "saved nested eta sweep on these exact bins; the clock has hard calls only. "
        "The legacy onset table uses Hiro Farre Josep Kaga annotations, compiled "
        "by labels\\_format.py and the category formatter (source\\_formatters). "
        "It counts original "
        "1 ms onsets in 50 ms bins, "
        "assigns category 1 for nonzero counts, deduplicates matching WPQH subsets, "
        "and compresses equal adjacent bins into half-open intervals. "
        "All elm-dsm variants use 60 of 124 inputs, no D-alpha input "
        "(pcphd02/03 mean-filled), 50 ms-mean serving of the 1 ms-trained source "
        "refit, and CO2 missing on 75/119 shots. Scores are offline: centered NBI "
        "smoothing adds 25 ms lookahead, so the refit is not a causal forecast. "
        "Every DSM variant uses upstream normalization computed before the source "
        "split, including blind-cohort source shots 190646 and 190532 "
        "(feature-statistics exposure). Detection heads use reviewed spans, and "
        "detection init retains the refit embedding. Numerical F1 and its interval "
        "are always shown; $^{\\dagger}$ denotes recall $\\geq0.99$, with P/R shown."
    )


def swap_caption(res: dict) -> str:
    return (
        f"ELM reference swap: {res['n_shots']} shots/{res['reviewed']['bins']} "
        "identical 50 ms bins wholly inside known review spans and analysed time, "
        "with DSM rows. Reviewed interval occupancy differs from legacy onset-bin "
        "presence; this restriction deviates from the AE all-frame audit. "
        + dsm_scope_caption(res)
        + interval_caption()
    )


def wrap_table(body: str, caption: str, label: str) -> str:
    return (
        "\\begin{table*}[t]\n\\centering\n\\small\n"
        + body
        + "\\caption{"
        + caption
        + "}\n\\label{"
        + label
        + "}\n"
        + "\\end{table*}\n"
    )
